apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-deploy
  namespace: apps-ns
  labels:
    app:  nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  nodeapp
    spec:
      containers:
      - name: docker
        image: docker:latest
        namespace: apps-ns
        command:
        - cat
        tty: true
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock         
        
      - name:  node-container
        image:  belalhany/iti_jenkins:3.1
        ports:
        - containerPort:  80
          name:  http
        - containerPort: 3000
        
        volumeMounts:
        - name: jenkins-pvc
          mountPath: /var/jenkins_home
        
      volumes:
        - name: jenkins-pvc
          persistentVolumeClaim:
            claimName: volume-claim
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock 


